"""图片模型目录数据。

自动生成，手动编辑无效。
"""

from __future__ import annotations

from pydantic import BaseModel


class ImageModelRecord(BaseModel):
    """图片模型记录。"""

    id: str
    name: str
    api: str
    provider: str
    base_url: str
    input: list[str]
    output: list[str]
    cost: dict[str, float]


IMAGE_MODELS: dict[str, dict[str, ImageModelRecord]] = {
    "openrouter": {
        "black-forest-labs/flux.2-flex": ImageModelRecord(
            id="black-forest-labs/flux.2-flex",
            name="Black Forest Labs: FLUX.2 Flex",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["image"],
            cost={"input": 0, "output": 0, "cache_read": 0, "cache_write": 0},
        ),
        "black-forest-labs/flux.2-klein-4b": ImageModelRecord(
            id="black-forest-labs/flux.2-klein-4b",
            name="Black Forest Labs: FLUX.2 Klein 4B",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["image"],
            cost={"input": 0, "output": 0, "cache_read": 0, "cache_write": 0},
        ),
        "black-forest-labs/flux.2-max": ImageModelRecord(
            id="black-forest-labs/flux.2-max",
            name="Black Forest Labs: FLUX.2 Max",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["image"],
            cost={"input": 0, "output": 0, "cache_read": 0, "cache_write": 0},
        ),
        "black-forest-labs/flux.2-pro": ImageModelRecord(
            id="black-forest-labs/flux.2-pro",
            name="Black Forest Labs: FLUX.2 Pro",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["image"],
            cost={"input": 0, "output": 0, "cache_read": 0, "cache_write": 0},
        ),
        "bytedance-seed/seedream-4.5": ImageModelRecord(
            id="bytedance-seed/seedream-4.5",
            name="ByteDance Seed: Seedream 4.5",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["image", "text"],
            output=["image"],
            cost={"input": 0, "output": 0, "cache_read": 0, "cache_write": 0},
        ),
        "google/gemini-2.5-flash-image": ImageModelRecord(
            id="google/gemini-2.5-flash-image",
            name="Google: Nano Banana (Gemini 2.5 Flash Image)",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["image", "text"],
            output=["image", "text"],
            cost={
                "input": 0.3,
                "output": 2.5,
                "cache_read": 0.03,
                "cache_write": 0.08333333333333334,
            },
        ),
        "google/gemini-3-pro-image": ImageModelRecord(
            id="google/gemini-3-pro-image",
            name="Google: Nano Banana Pro (Gemini 3 Pro Image)",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["image", "text"],
            output=["image", "text"],
            cost={
                "input": 2,
                "output": 12,
                "cache_read": 0.19999999999999998,
                "cache_write": 0.375,
            },
        ),
        "google/gemini-3-pro-image-preview": ImageModelRecord(
            id="google/gemini-3-pro-image-preview",
            name="Google: Nano Banana Pro (Gemini 3 Pro Image Preview)",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["image", "text"],
            output=["image", "text"],
            cost={
                "input": 2,
                "output": 12,
                "cache_read": 0.19999999999999998,
                "cache_write": 0.375,
            },
        ),
        "google/gemini-3.1-flash-image": ImageModelRecord(
            id="google/gemini-3.1-flash-image",
            name="Google: Nano Banana 2 (Gemini 3.1 Flash Image)",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["image", "text"],
            output=["image", "text"],
            cost={"input": 0.5, "output": 3, "cache_read": 0, "cache_write": 0},
        ),
        "google/gemini-3.1-flash-image-preview": ImageModelRecord(
            id="google/gemini-3.1-flash-image-preview",
            name="Google: Nano Banana 2 (Gemini 3.1 Flash Image Preview)",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["image", "text"],
            output=["image", "text"],
            cost={"input": 0.5, "output": 3, "cache_read": 0, "cache_write": 0},
        ),
        "google/gemini-3.1-flash-lite-image": ImageModelRecord(
            id="google/gemini-3.1-flash-lite-image",
            name="Google: Nano Banana 2 Lite (Gemini 3.1 Flash Lite Image)",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["image", "text"],
            output=["image", "text"],
            cost={"input": 0.25, "output": 1.5, "cache_read": 0, "cache_write": 0},
        ),
        "krea/krea-2-large": ImageModelRecord(
            id="krea/krea-2-large",
            name="Krea: Krea 2 Large",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["image"],
            cost={"input": 0, "output": 0, "cache_read": 0, "cache_write": 0},
        ),
        "krea/krea-2-medium": ImageModelRecord(
            id="krea/krea-2-medium",
            name="Krea: Krea 2 Medium",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["image"],
            cost={"input": 0, "output": 0, "cache_read": 0, "cache_write": 0},
        ),
        "krea/krea-2-medium-turbo": ImageModelRecord(
            id="krea/krea-2-medium-turbo",
            name="Krea: Krea 2 Medium Turbo",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["image"],
            cost={"input": 0, "output": 0, "cache_read": 0, "cache_write": 0},
        ),
        "microsoft/mai-image-2.5": ImageModelRecord(
            id="microsoft/mai-image-2.5",
            name="Microsoft: MAI-Image-2.5",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["image"],
            cost={"input": 5, "output": 0, "cache_read": 0, "cache_write": 0},
        ),
        "microsoft/mai-image-2.5-pro": ImageModelRecord(
            id="microsoft/mai-image-2.5-pro",
            name="Microsoft: MAI-Image-2.5 Pro",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["image"],
            cost={"input": 5, "output": 0, "cache_read": 0, "cache_write": 0},
        ),
        "openai/gpt-5-image": ImageModelRecord(
            id="openai/gpt-5-image",
            name="OpenAI: GPT-5 Image",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["image", "text"],
            output=["image", "text"],
            cost={"input": 10, "output": 10, "cache_read": 1.25, "cache_write": 0},
        ),
        "openai/gpt-5-image-mini": ImageModelRecord(
            id="openai/gpt-5-image-mini",
            name="OpenAI: GPT-5 Image Mini",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["image", "text"],
            output=["image", "text"],
            cost={"input": 2.5, "output": 2, "cache_read": 0.25, "cache_write": 0},
        ),
        "openai/gpt-5.4-image-2": ImageModelRecord(
            id="openai/gpt-5.4-image-2",
            name="OpenAI: GPT-5.4 Image 2",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["image", "text"],
            output=["image", "text"],
            cost={"input": 8, "output": 15, "cache_read": 2, "cache_write": 0},
        ),
        "openai/gpt-image-1": ImageModelRecord(
            id="openai/gpt-image-1",
            name="OpenAI: GPT Image 1",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["image"],
            cost={"input": 10, "output": 10, "cache_read": 1.25, "cache_write": 0},
        ),
        "openai/gpt-image-1-mini": ImageModelRecord(
            id="openai/gpt-image-1-mini",
            name="OpenAI: GPT Image 1 Mini",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["image"],
            cost={"input": 2.5, "output": 2.5, "cache_read": 0.25, "cache_write": 0},
        ),
        "openai/gpt-image-2": ImageModelRecord(
            id="openai/gpt-image-2",
            name="OpenAI: GPT Image 2",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["image"],
            cost={"input": 8, "output": 8, "cache_read": 2, "cache_write": 0},
        ),
        "openrouter/auto": ImageModelRecord(
            id="openrouter/auto",
            name="Auto Router",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["text", "image"],
            cost={
                "input": -1000000,
                "output": -1000000,
                "cache_read": 0,
                "cache_write": 0,
            },
        ),
        "openrouter/auto-beta": ImageModelRecord(
            id="openrouter/auto-beta",
            name="Auto Router (Beta)",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["text", "image"],
            cost={
                "input": -1000000,
                "output": -1000000,
                "cache_read": 0,
                "cache_write": 0,
            },
        ),
        "recraft/recraft-v3": ImageModelRecord(
            id="recraft/recraft-v3",
            name="Recraft: Recraft V3",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["image"],
            cost={"input": 0, "output": 0, "cache_read": 0, "cache_write": 0},
        ),
        "recraft/recraft-v4": ImageModelRecord(
            id="recraft/recraft-v4",
            name="Recraft: Recraft V4",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["image"],
            cost={"input": 0, "output": 0, "cache_read": 0, "cache_write": 0},
        ),
        "recraft/recraft-v4-pro": ImageModelRecord(
            id="recraft/recraft-v4-pro",
            name="Recraft: Recraft V4 Pro",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["image"],
            cost={"input": 0, "output": 0, "cache_read": 0, "cache_write": 0},
        ),
        "recraft/recraft-v4-pro-vector": ImageModelRecord(
            id="recraft/recraft-v4-pro-vector",
            name="Recraft: Recraft V4 Pro Vector",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["image"],
            cost={"input": 0, "output": 0, "cache_read": 0, "cache_write": 0},
        ),
        "recraft/recraft-v4-vector": ImageModelRecord(
            id="recraft/recraft-v4-vector",
            name="Recraft: Recraft V4 Vector",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["image"],
            cost={"input": 0, "output": 0, "cache_read": 0, "cache_write": 0},
        ),
        "recraft/recraft-v4.1": ImageModelRecord(
            id="recraft/recraft-v4.1",
            name="Recraft: Recraft V4.1",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["image"],
            cost={"input": 0, "output": 0, "cache_read": 0, "cache_write": 0},
        ),
        "recraft/recraft-v4.1-pro": ImageModelRecord(
            id="recraft/recraft-v4.1-pro",
            name="Recraft: Recraft V4.1 Pro",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["image"],
            cost={"input": 0, "output": 0, "cache_read": 0, "cache_write": 0},
        ),
        "recraft/recraft-v4.1-pro-vector": ImageModelRecord(
            id="recraft/recraft-v4.1-pro-vector",
            name="Recraft: Recraft V4.1 Pro Vector",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["image"],
            cost={"input": 0, "output": 0, "cache_read": 0, "cache_write": 0},
        ),
        "recraft/recraft-v4.1-utility": ImageModelRecord(
            id="recraft/recraft-v4.1-utility",
            name="Recraft: Recraft V4.1 Utility",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["image"],
            cost={"input": 0, "output": 0, "cache_read": 0, "cache_write": 0},
        ),
        "recraft/recraft-v4.1-utility-pro": ImageModelRecord(
            id="recraft/recraft-v4.1-utility-pro",
            name="Recraft: Recraft V4.1 Utility Pro",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["image"],
            cost={"input": 0, "output": 0, "cache_read": 0, "cache_write": 0},
        ),
        "recraft/recraft-v4.1-vector": ImageModelRecord(
            id="recraft/recraft-v4.1-vector",
            name="Recraft: Recraft V4.1 Vector",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["image"],
            cost={"input": 0, "output": 0, "cache_read": 0, "cache_write": 0},
        ),
        "sourceful/riverflow-v2-fast": ImageModelRecord(
            id="sourceful/riverflow-v2-fast",
            name="Sourceful: Riverflow V2 Fast",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["image"],
            cost={"input": 0, "output": 0, "cache_read": 0, "cache_write": 0},
        ),
        "sourceful/riverflow-v2-pro": ImageModelRecord(
            id="sourceful/riverflow-v2-pro",
            name="Sourceful: Riverflow V2 Pro",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["image"],
            cost={"input": 0, "output": 0, "cache_read": 0, "cache_write": 0},
        ),
        "sourceful/riverflow-v2.5-fast": ImageModelRecord(
            id="sourceful/riverflow-v2.5-fast",
            name="Sourceful: Riverflow V2.5 Fast",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["image"],
            cost={"input": 0, "output": 0, "cache_read": 0, "cache_write": 0},
        ),
        "sourceful/riverflow-v2.5-pro": ImageModelRecord(
            id="sourceful/riverflow-v2.5-pro",
            name="Sourceful: Riverflow V2.5 Pro",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["image"],
            cost={"input": 0, "output": 0, "cache_read": 0, "cache_write": 0},
        ),
        "x-ai/grok-imagine-image-quality": ImageModelRecord(
            id="x-ai/grok-imagine-image-quality",
            name="xAI: Grok Imagine Image Quality",
            api="openrouter-images",
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            input=["text", "image"],
            output=["image"],
            cost={"input": 0, "output": 0, "cache_read": 0, "cache_write": 0},
        ),
    },
}
